### DISCUSSION TITLE
More on styling

### DISCUSSION THREAD

**Discussion by jonasthewolf** [jonasthewolf/gsn2x#367] [Q&A]
This discussion started as part of #358.

Here is the relevant part:

I just checked it. now the layer thing is working fine. But the text is still rendered in white. I did some testing and figured out that if I am including option "url", then the text is rendered white. If the URL is removed than it is fine.

eg:
```yaml
G0-TopLevelGoal:
  text: It is OK to use to develop this functionality/application(because)
  inContextOf: [A1]
  supportedBy: [S1]
  status: draft
  classes: [status-yellow]
A1:
  text: This function/application itself is safe and secure
  status: draft
  url: https://example.com/
S1:
  text: Argue over all engineering steps* where data* is manipulated/created/.
  supportedBy: [G1, G2, G3, G4, G5, G6, G7]
  inContextOf: [C1, C2]
  status: draft
C1:
  text: All relevant data* is known
  status: draft
C2:
  text: All relevant steps* are identified
  url: https://example.com/
  status: draft
```

![image](https://github.com/jonasthewolf/gsn2x/assets/16023405/1601dd22-d106-4e2b-afd1-69a23d32fde0)

sure. here is the content of css file.

```css
.status-normal path { fill: white; }
.status-normal text,a { fill: black; }
.status-green path { fill: green; }
.status-green text,a { fill: black; }
.status-yellow path { fill: orange; }
.status-yellow text,a { fill: black; }
.status-red path { fill: red; }
.status-red text,a { fill: white; }
g:hover {stroke: black;}
```

Moreover, Rlaks10 is interested in styling the architecture view.
