### ISSUE TITLE
Strategies as interfaces in Argument View are not linked

### ISSUE THREAD

**Issue by jonasthewolf** [jonasthewolf/gsn2x#127]

**Comment by jonasthewolf** [comment]
There is no notion of "away strategies".

template.yaml
```
module:
  name: template
  brief: template

G1:
  text: Top-level
  supportedBy: [S1]
```

instance.yaml
```
module:
  name: inst1
  brief: Instance 1

S1: 
  text: Strategy
  supportedBy: [G2]

G2:
  text: Goal 2
  supportedBy: [Sn1]

Sn1:
  text: Abcdefg
```
