### ISSUE TITLE
Indefinite movement of nodes to the right.

### ISSUE THREAD

**Issue by jonasthewolf** [jonasthewolf/gsn2x#150]
The rest of the image seems to move away indefinitely.

**Comment by jonasthewolf** [comment]
Example that moves indefinitely:

```

G1:
  text: G1
  supportedBy: [G2, G3, G4]

G2:
  text: G2
  supportedBy: [Sn3, Sn4]

G3:
  text: G3
  supportedBy: [Sn1]

G4:
  text: G4
  supportedBy: [Sn2, Sn3, Sn4]

Sn1:
  text: Sn1

Sn2:
  text: Sn2

Sn3:
  text: Sn3

Sn4:
  text: Sn4
```

Problem is that there is a n:m relation between goals and solutions.
Can be solved by modifying the names of the goals to influence sorting order.

**Comment by jonasthewolf** [comment]
Can be fixed e.g. this way:

```

G1:
  text: G1
  supportedBy: [G2, G1a, G4]

G2:
  text: G2
  supportedBy: [Sn3, Sn4]

G1a:
  text: G3
  supportedBy: [Sn1]

G4:
  text: G4
  supportedBy: [Sn5, Sn3, Sn4]

Sn1:
  text: Sn1

Sn5:
  text: Sn5

Sn3:
  text: Sn3

Sn4:
  text: Sn4

```
