### ISSUE TITLE
SVG Rendering - Gravity Suggestion

### ISSUE THREAD

**Issue by jsavage** [jonasthewolf/gsn2x#173]
Hi @jonasthewolf,
This is a minor observation.
While in general the generated SVG is pleasing to the eye and intuitive, here are a couple of examples where the layout is less intuitive.
![image](https://user-images.githubusercontent.com/189524/194906014-8e957f65-1b1d-4708-8ea2-a0239baae409.png)
Hopefully you can see the issue without being able to read the underlying text. 

I wonder whether gravity might encourage a more pleasing result.

**Comment by jsavage** [comment]
Ah, I have just seen your note that  "The order of the GSN elements on the same horizontal rank can be influenced by their ID. The elements are sorted lexicographically. Thus, a goal G1 if placed on the same vertical level is placed before G2." Will take a closer look at the YAML to see if this is causing the lower of the above issues.

**Comment by jonasthewolf** [comment]
I checked your minimal example:
If you replace the Sn216 with Snx216, the rendering appears as I guess you would expect it.
I am glad you found the place in the documentation, that I tried to explain how to solve such issues.

```
G5:
  text: Rationale
  supportedBy: [Sn227, Sn211]

G8:
  text: Completeness of HSRs
  supportedBy: [Snx216, Sn227]

Snx216:
  text: HSRs

Sn227:
  text: Requirements Traceability Reports
  url: txt

Sn211:
  text: TSRs Report
  url: txt
```
