### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by jonasthewolf** [jonasthewolf/gsn2x#192]
@jonasthewolf 
something is causing this latest release (v2.5.1) to break when to ingesting my example.  Two previous releases still accept this yaml but not this one.  Your own example.yaml looks ok too.
V2.4.3 is the most recent formal Release that doesn't have this issue.
Not had a chance to dig further but this is one example that it doesnt like. The SVG is created but displays no graphics.
  [jsexample1.5-db.zip](https://github.com/jonasthewolf/gsn2x/files/9838223/jsexample1.5-db.zip)
FYI I am using the windows build only. I drag and drop the YAML file onto the exe and then insect the SVG.  If there is a log file I have not found it.
[jsexample1.51-Copy.svg.zip](https://github.com/jonasthewolf/gsn2x/files/9900638/jsexample1.51-Copy.svg.zip)

__Originally posted by @jsavage in https://github.com/jonasthewolf/gsn2x/issues/173#issuecomment-1296938243__

**Comment by jsavage** [comment]
I can now see the error is : ![image](https://user-images.githubusercontent.com/189524/199076130-923d70bf-2c19-443d-8e80-69d976b4812c.png)
Unfortunately Readme.md refers to itself for advice on this point

**Comment by jonasthewolf** [comment]
Hi @jsavage, I opened this issue here.
I wil have a deeper look into the problem. Thanks for providing the example.
There are multiple issues here:
1) My algorithm infinitely tries to place nodes correctly. That's the message.
2) The Sn301 and Sn229 should be placed on a far lower rank than it actually is.
Maybe the first is a consequence of the second. I will try to figure that out.

**Comment by jonasthewolf** [comment]
Minimal example (extracted from provided sample):

```
G1:
  text: G1
  supportedBy: [G6, G7]

G6:
  text: G6
  supportedBy: [Sn2, Sn3, Sn1]

Sn1:
  text: Sn1

Sn2:
  text: Sn2

Sn3:
  text: Sn3

G7:
  text: G7
  supportedBy: [G13]

G13:
  text: G13.
  supportedBy: [G20]

G20:
  text: G20.
  supportedBy: [Sn2, Sn3, Sn4]

Sn4:
  text: Sn4
```
