### ISSUE TITLE
Layout with multiple contexts and single child does not work

### ISSUE THREAD

**Issue by jonasthewolf** [jonasthewolf/gsn2x#249]
**Describe the bug**
G4 is not directly under G3.

**To Reproduce**
This is a minimal YAML that reproduces the example:
```
G3:
  text: Yet another goal with context
  inContextOf: [J2, A2]
  supportedBy: [G4]

A2:
  text: Another assumption

J2:
  text: Another justification

G4:
  text: Simple goal
  supportedBy: [Sn1]

Sn1:
  text: A solution

```

**Expected behavior**
G4 should be directly under G3.

**Desktop (please complete the following information):**
not relevant
