### ISSUE TITLE
Layout with multiple context nodes does not work correctly

### ISSUE THREAD

**Issue by jonasthewolf** [jonasthewolf/gsn2x#250]
**Describe the bug**
There is a line from G2 to A2 crossing G3.

**To Reproduce**
This is a minimal YAML that reproduces the example:
```
G1:
  text: G1
  supportedBy: [G2, G3]

G2:
  text: G2
  inContextOf: [A2]
  undeveloped: true

G3:
  text: G3
  inContextOf: [J2, A2]
  supportedBy: [G4]

A2:
  text: A2

J2:
  text: J2

G4:
  text: G4
  undeveloped: true
```

**Expected behavior**
A2 and J2 should be exchanged. Then everything would be correctly displayed.

**Desktop (please complete the following information):**
not relevant

**Additional context**
n/a
