### ISSUE TITLE
Links in architecture.svg do not respect relative paths.

### ISSUE THREAD

**Issue by jonasthewolf** [jonasthewolf/gsn2x#254]
**Describe the bug**
See description

**To Reproduce**
a/b/c.yml:
```yaml
G1:
  text: G1
  supportedBy: [G2]
```

d.yml
```yaml
G2:
  text: G2
  undeveloped:true
```

**Expected behavior**
Links in `architecture.svg` navigate to the respective module view.

**Screenshots**
not relevant

**Desktop (please complete the following information):**
not relevant
