### ISSUE TITLE
Add undeveloped strategies again.

### ISSUE THREAD

**Issue by jonasthewolf** [jonasthewolf/gsn2x#255]
**Describe the bug**
Undeveloped strategies are not shown correctly.

**To Reproduce**
This is a minimal YAML that reproduces the example:
```yaml
G1:
  text: G1
  supportedBy: [S1]
S1:
  text: S1
  undeveloped: true
```

**Expected behavior**
Undeveloped strategies should be displayed again with the undeveloped diamond.

**Screenshots**
not needed

**Desktop (please complete the following information):**
not relevant
