### ISSUE TITLE
Chinese characters tend to go outside the element range

### ISSUE THREAD

**Issue by TysonSir** [jonasthewolf/gsn2x#342]
**Describe the bug**

Chinese characters tend to go outside the element range.

**To Reproduce**

This is a minimal YAML that reproduces the example:

```yaml
G1:
 text: 这是超过10个中文汉字的一句话
 supportedBy: [S1]
 inContextOf: [A1]
 classes: [additionalclass1, additionalclass2]

S1:
 text: 这是超过20个中文汉字的一句话，这是超过20个中文汉字的一句话
 supportedBy: [G2,G3]

A1: 
 text: This is a sentence in more than 10 Chinese characters

G2:
 text: Subgoal 1
 inContextOf: [J1]
 undeveloped: true

G3:
 text: Subgoal 2
 supportedBy: [Sn1] 
 inContextOf: [J1,C1]

Sn1: 
 text: 这是超过10个中文汉字的一句话
 url: https://github.com/jonasthewolf/gsn2x

J1: 
 text: 这是超过10个中文汉字的一句话

C1:
 text: 这是超过10个中文汉字的一句话

```

You can sanitize your files from your intellectual property using, e.g. https://mikefarah.gitbook.io/yq/

```
 yq "(.[] | select(. | has(\"text\"))) .text |=sub(\"[a-zA-Z0-9]\",\"x\")"  inputfile.yaml | yq "... comments=\"\"" > outputfile.yaml
```

**Expected behavior**

- Chinese characters do not overflow element range.

- The width of each element can be set, which is very helpful for beautifying the whole graph.

**Screenshots**

![image](https://github.com/jonasthewolf/gsn2x/assets/38468969/10c534f0-894a-49b4-a5f2-d21d488b39b5)

**Desktop (please complete the following information):**

 - OS: [Windows]
 - OS Version: [11]
 - SVG Viewer: [browser Chrome that is used for viewing the SVG]
 - gsn2x Version: [gsn2x 3.0.0]

**Additional context**
I am working on a graphical assurance case tool based on gsn2x.
gsn2x is a great tool for me.
Thanks to all the developers and support staff.

**Comment by TysonSir** [comment]
![image](https://github.com/jonasthewolf/gsn2x/assets/38468969/1716a900-61a1-49c7-95b7-ad41864b1e6a)
I sincerely apologize for not noticing the addition of the new '-w' parameter earlier. It effectively addresses my second expectation, which is the ability to set the width of each element. However, it seems that **the '-w' parameter does not support Chinese characters**. As illustrated in the image, I set '-w 8', and while the English element A1 is appropriately formatted, the remaining Chinese elements remain unchanged.

**Comment by jonasthewolf** [comment]
Thanks for the feedback.
Let me see if I can do something this weekend.

**Comment by jonasthewolf** [comment]
I think I know where the problem is:
Can you introduce whitespace between words? That should already fix it.

**Comment by TysonSir** [comment]
Thanks! I followed your advice and threw in some spaces between words, and it did the trick!  I get that Chinese sentences usually roll without spaces, but I sprinkled them in where needed.

**Comment by jonasthewolf** [comment]
Thanks for the info.
How do you do line wrapping in Chinese if you don't use white space?
Ar any character? Huge dictionary?

I will document that a bit better.
You can use e.g. that syntax:

```yaml
G1:
  text: |
    Multiline text with
    breaks preserved
```
