### ISSUE TITLE
Suggestion: Addition of a second textual area for each GSN object

### ISSUE THREAD

**Issue by jsavage** [jonasthewolf/gsn2x#75]
Many thanks for sharing this BTW.   
As a GSN author, in the top row of each object I would like to be able to (optionally) include a short name or title for my goals, concepts etc to provide a second level of detail.  I would suggest separating this from the reference with a ':' and using the same font as the Reference.
The optional title could be specified using keyword 'title:' as per 'text:' 
A smaller font could then be used for the 'text'

**Comment by jonasthewolf** [comment]
@jsavage actually, I am trying to follow the standard closely.

Would you be looking for something like this?

```
G0:
  text: Short Goal
  supportedBy: [G1-MyMoreDetailedExplanation]

G1-MyMoreDetailedExplanation:
  text: This is an even more detailed explanation of the goal.
  undeveloped: true
````
