### ISSUE TITLE
Ranking in architecture view creates edges that overlap nodes.

### ISSUE THREAD

**Issue by jonasthewolf** [jonasthewolf/gsn2x#84]
Maybe a solution is to draw edges in a more complex way. When drawing edges, nodes are already placed and their size is known.

**Comment by jonasthewolf** [comment]
Associated problem:

```

G1:
  text: G1
  supportedBy: [Sn1, G2]

G2:
  text: G2
  supportedBy: [G3]

G3:
  text: G3
  supportedBy: [G4]

G4:
  text: G4
  supportedBy: [Sn1]

Sn1:
  text: Sn1
```

**Comment by jonasthewolf** [comment]
Associated problem:

```

G1:
  text: G1
  supportedBy: [Sn1, G2]
  level: x

G2:
  text: G2
  supportedBy: [G3]
  level: x

G3:
  text: G3
  supportedBy: [G4]
  level: x

G4:
  text: G4
  supportedBy: [Sn1]
  level: x
  
Sn1:
  text: Sn1
```

Result: Endless loop...

**Comment by jonasthewolf** [comment]
Associated problem:

```

G1:
  text: G1
  supportedBy: [Sn1, G2]
  level: x

G2:
  text: G2
  supportedBy: [G3]
  level: x

G3:
  text: G3
  supportedBy: [G4]

G4:
  text: G4
  supportedBy: [Sn1]

Sn1:
  text: Sn1
```

Result: Rendering a diagram took too many iterations (50). See README.md for hints how to solve this situation.

**Comment by jonasthewolf** [comment]
Associated problem:

```

G1:
  text: G1
  supportedBy: [Sn1, G2]
  level: x

G2:
  text: G2
  supportedBy: [G3]

G3:
  text: G3
  supportedBy: [G4]
  level: x

G4:
  text: G4
  supportedBy: [Sn1]
  level: x

Sn1:
  text: Sn1
```

Result: crash!

thread 'main' panicked at 'attempt to add with overflow', src/dirgraphsvg/graph.rs:182:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
   3: gsn2x::dirgraphsvg::graph::NodeInfoMap::constrain_by_forced_levels
             at ./src/dirgraphsvg/graph.rs:182:41
   4: gsn2x::dirgraphsvg::graph::NodeInfoMap::new
             at ./src/dirgraphsvg/graph.rs:143:13
   5: gsn2x::dirgraphsvg::graph::rank_nodes
             at ./src/dirgraphsvg/graph.rs:378:25
   6: gsn2x::dirgraphsvg::DirGraph::layout
             at ./src/dirgraphsvg/mod.rs:153:21
   7: gsn2x::dirgraphsvg::DirGraph::write
             at ./src/dirgraphsvg/mod.rs:124:16
   8: gsn2x::render::render_argument
             at ./src/render.rs:464:5
   9: gsn2x::print_outputs
             at ./src/main.rs:354:13
  10: gsn2x::main
             at ./src/main.rs:201:9
  11: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
