### ISSUE TITLE
Fix placement of solutions with multiple parents.

### ISSUE THREAD

**Issue by jonasthewolf** [jonasthewolf/gsn2x#87]
```
G0:
  text: a
  supportedBy: [G1, G2, G3]

G1: 
  text: b
  supportedBy: [G4]

G2:
  text: d
  supportedBy: [Sn1]

G3:
  text: d
  supportedBy: [Sn1]

Sn1:
  text: c

G4:
  text: e
  supportedBy: [Sn1]
```

Sn1 should be one rank lower than G4.
